name: cm3070-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - pydicom
  - gudhi
  - pip:
      - tensorflow[and-cuda]
      - opencv-python
